### ISSUE TITLE
Connect backend (mongoDB Atlas) to frontend (react js)

### ISSUE THREAD

**Issue by nugentmichael1** [Spring2022-CSCI152/Team6#2]

**Comment by vinguyen12** [comment]
Lee got the database on Mongo Compass connected with our JavaScript by adding a server.js file and run it by node.js. The next step is set the js files to run through the server.js file to connect to the database.

**Comment by nugentmichael1** [comment]
Vi got Postman (a 3rd party service?) to make post requests to the database.  Still need to import this functionality to front-end (react).

**Comment by vinguyen12** [comment]
Yes. I used Postman to send a request to the server for testing if the server is responsive to our localhost. The server is responsive, and the front-end team is able to do POST/GET with the server now, but I'm still trying to figure out the general way (syntax) to do it in the front-end.
